### ISSUE TITLE
0.1.0 version  mma-server start error

### ISSUE THREAD

**Issue by freeshow** [aliyun/alibabacloud-maxcompute-tool-migrate#62]
**Describe the bug**

**To Reproduce**
/path/to/mma/bin/mma-server start error

**Expected behavior**
2021-09-27 09:30:59,894 INFO  [main] resource.MmaResourceManager (MmaResourceManager.java:update(108)) - Update resource map, key: DATA_WORKER, before: null, after: 25
2021-09-27 09:30:59,898 INFO  [main] resource.MmaResourceManager (MmaResourceManager.java:update(108)) - Update resource map, key: METADATA_WORKER, before: null, after: 5
2021-09-27 09:31:00,813 INFO  [main] util.log (Log.java:initialized(170)) - Logging initialized @1670ms to org.eclipse.jetty.util.log.Slf4jLog
2021-09-27 09:31:00,882 ERROR [main] server.MmaServerMain (MmaServerMain.java:main(96)) - Failed to start MMA server
java.lang.SecurityException: class "javax.servlet.FilterRegistration"'s signer information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:898) ~[?:1.8.0_181]
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:761) ~[?:1.8.0_181]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_181]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_181]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_181]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_181]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_181]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:153) ~[jetty-servlet-9.4.41.v20210516.jar:9.4.41.v20210516]
        at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:146) ~[jetty-servlet-9.4.41.v20210516.jar:9.4.41.v20210516]
        at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:141) ~[jetty-servlet-9.4.41.v20210516.jar:9.4.41.v20210516]
        at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:116) ~[jetty-servlet-9.4.41.v20210516.jar:9.4.41.v20210516]
        at com.aliyun.odps.mma.server.ui.MmaApi.<init>(MmaApi.java:45) ~[mma-server-0.1.0.jar:?]
        at com.aliyun.odps.mma.server.MmaServer.<init>(MmaServer.java:50) ~[mma-server-0.1.0.jar:?]
        at com.aliyun.odps.mma.server.MmaServerMain.main(MmaServerMain.java:93) [mma-server-0.1.0.jar:?]
2021-09-27 09:31:00,887 INFO  [EventHandling] event.MmaEventManager (MmaEventManager.java:run(108)) - EventHandling thread starts

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  centos7
 - jdk 8

**Comment by cornmonster** [comment]
@idleyui Looks like a dependency conflict.
